config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resource :like
    resource :retweet
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true

  after_create_commit { broadcast_prepend_to 'posts' }
  after_update_commit { broadcast_update_to 'posts' }
  after_destroy_commit { broadcast_remove_to 'posts' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @post.increment! :likes
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  def index
    @post = Post.new
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@post, partial: 'posts/form', locals: { post: @post })
        end
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:body, :likes, :retweets)
  end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :set_post

  def create
    @post.increment! :retweets
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <% if flash[:notice] %>
        <div class=""><%= flash[:notice] %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, id: dom_id(post), class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_field :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
  <div id="<%= dom_id post %>" class="flex p-5 flex-col rounded-md border border-gray-200 outline-none items-start my-5">
    <p class="my-5 text-xl font-semibold">
      <%= post.body %>
    </p>

    <div class="my-5 flex">
      <%= button_to "Likes (#{post.likes || 0})", post_like_path(post), method: :post, class: "mr-2 text-blue-500" %>
      <%= button_to "Retweets (#{post.retweets || 0})", post_retweet_path(post), method: :post %>
    </div>

    <%= link_to 'Edit this post', edit_post_path(post), class: "justify-self-start rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= turbo_frame_tag dom_id(@post) do %>
    <div class="flex p-5 flex-col rounded-md border border-gray-200 outline-none my-5">
      <%= render "form", post: @post %>
      <%= link_to "Cancel", @post, class: "m-2" %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= turbo_stream_from 'posts' %>
<div class="w-full">
  <h1 class="text-4xl my-5 font-bold">Posts</h1>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <%= turbo_frame_tag 'post_form' do %>
    <%= render 'form', post: @post %>
  <% end %>

  
  <div id="posts" class="min-w-full">
    <%= turbo_frame_tag "posts" do %>
      <%= render @posts %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    
    <%= turbo_frame_tag dom_id(@post) do %>
      <%= render @post %>
    <% end %>

    <% if action_name == "show" %>
      <div class="inline-block ml-2">
        <%= button_to 'Destroy this post', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
      <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>
</div>